{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b70283e6-7a20-4245-8199-4805038c5d9b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📡 Veriler çekiliyor ve işleniyor...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/r8/gv1b6vcn78z36zzjplfkymq00000gn/T/ipykernel_21337/525288505.py:436: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.\n",
      "  df_uscpi['MoM'] = df_uscpi[col_name].pct_change(1)*100\n",
      "/var/folders/r8/gv1b6vcn78z36zzjplfkymq00000gn/T/ipykernel_21337/525288505.py:437: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.\n",
      "  df_uscpi['YoY'] = df_uscpi[col_name].pct_change(12)*100\n",
      "/var/folders/r8/gv1b6vcn78z36zzjplfkymq00000gn/T/ipykernel_21337/525288505.py:455: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.\n",
      "  m.fillna(method='ffill', inplace=True)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ GÜNCELLENDİ!\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "import pandas as pd\n",
    "import os\n",
    "import io\n",
    "import math\n",
    "from datetime import datetime\n",
    "\n",
    "# --- AYARLAR ---\n",
    "# API Key'i GitHub Secrets'tan alacağız, eğer bulamazsa (lokalde çalışırken) senin yazdığını kullanır.\n",
    "API_KEY = os.environ.get(\"EVDS_API_KEY\", \"eEojQT7PgD\") \n",
    "START_DATE = \"01-01-2021\"\n",
    "# Bitiş tarihini dinamik yapmak daha iyidir, her gün güncelleneceği için bugünün tarihini alabiliriz.\n",
    "# Ama senin formatın sabitse böyle de kalabilir.\n",
    "END_DATE = datetime.now().strftime(\"%d-%m-%Y\")\n",
    "\n",
    "# EXCEL DOSYA YOLLARI (Direkt ana dizinden okuyacak)\n",
    "PATH_BUTCE = \"Merkezi Yönetim Bütçe Dengesi.xlsx\"\n",
    "PATH_NAKIT = \"Nakit Dengesi.xlsx\"\n",
    "PATH_ATIL = \"atılisgucu.xlsx\"\n",
    "PATH_PMI = \"imalat sanayi pmi.xlsx\"\n",
    "PATH_GSYH_ONCU = \"GSYH_Oncu.xlsx\"\n",
    "\n",
    "headers = {\"key\": API_KEY, \"User-Agent\": \"Mozilla/5.0\"}\n",
    "requests.packages.urllib3.disable_warnings()\n",
    "\n",
    "# --- YARDIMCI FONKSİYONLAR ---\n",
    "def clean_nan(value):\n",
    "    \"\"\"NaN değerleri None (null) yapar, böylece JSON bozulmaz.\"\"\"\n",
    "    if isinstance(value, float):\n",
    "        if math.isnan(value) or math.isinf(value):\n",
    "            return None\n",
    "    return value\n",
    "\n",
    "def veri_cek_evds(series_code, aylik_yap=False):\n",
    "    url = f\"https://evds2.tcmb.gov.tr/service/evds/series={series_code}&startDate={START_DATE}&endDate={END_DATE}&type=json\"\n",
    "    if aylik_yap: url += \"&frequency=5&aggregationTypes=avg\"\n",
    "    try:\n",
    "        resp = requests.get(url, headers=headers, verify=False)\n",
    "        data = resp.json()\n",
    "        return data[\"items\"] if \"items\" in data else []\n",
    "    except: return []\n",
    "\n",
    "def veri_cek_fred(series_id):\n",
    "    try:\n",
    "        url = f\"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}\"\n",
    "        resp = requests.get(url, headers={\"User-Agent\": \"Mozilla/5.0\"}, verify=False)\n",
    "        if resp.status_code == 200:\n",
    "            df = pd.read_csv(io.StringIO(resp.text))\n",
    "            df.columns = [c.strip() for c in df.columns]\n",
    "            \n",
    "            # Tarih sütunu düzeltme\n",
    "            if 'observation_date' in df.columns:\n",
    "                df.rename(columns={'observation_date': 'DATE'}, inplace=True)\n",
    "            \n",
    "            if 'DATE' in df.columns:\n",
    "                df['DATE'] = pd.to_datetime(df['DATE'])\n",
    "                return df\n",
    "    except: pass\n",
    "    return pd.DataFrame()\n",
    "\n",
    "print(\"📡 Veriler çekiliyor ve işleniyor...\")\n",
    "\n",
    "# ==========================================\n",
    "# 1. MAKROEKONOMİK BİRİNCİL GÖSTERGELER\n",
    "# ==========================================\n",
    "\n",
    "# --- A) GSYH ---\n",
    "gsyh_list = []\n",
    "gsyh_raw = veri_cek_evds(\"TP.GSYIH26.IFK.ZH\")\n",
    "if gsyh_raw:\n",
    "    temp_vals = [float(x[\"TP_GSYIH26_IFK_ZH\"]) for x in gsyh_raw if x.get(\"TP_GSYIH26_IFK_ZH\")]\n",
    "    temp_dates = [x[\"Tarih\"] for x in gsyh_raw if x.get(\"TP_GSYIH26_IFK_ZH\")]\n",
    "    for i in range(len(temp_vals)):\n",
    "        if \"2023\" in temp_dates[i] or \"2024\" in temp_dates[i] or \"2025\" in temp_dates[i]:\n",
    "            yillik = ((temp_vals[i] - temp_vals[i-4])/temp_vals[i-4])*100 if i>=4 else 0\n",
    "            gsyh_list.append({\"tarih\": temp_dates[i], \"yillik\": round(yillik, 1)})\n",
    "\n",
    "# --- B) TÜFE ---\n",
    "tufe_list = []\n",
    "tufe_raw = veri_cek_evds(\"TP.FG.J0\")\n",
    "if tufe_raw:\n",
    "    vals = [float(x[\"TP_FG_J0\"]) for x in tufe_raw if x.get(\"TP_FG_J0\")]\n",
    "    dates = [x[\"Tarih\"] for x in tufe_raw if x.get(\"TP_FG_J0\")]\n",
    "    for i in range(len(vals)):\n",
    "        if \"2023\" in dates[i] or \"2024\" in dates[i] or \"2025\" in dates[i]:\n",
    "            aylik = ((vals[i] - vals[i-1])/vals[i-1])*100 if i>0 else 0\n",
    "            yillik = ((vals[i] - vals[i-12])/vals[i-12])*100 if i>=12 else 0\n",
    "            tufe_list.append({\"tarih\": dates[i], \"aylik\": round(aylik, 2), \"yillik\": round(yillik, 2)})\n",
    "\n",
    "# --- C) Yİ-ÜFE ---\n",
    "ufe_list = []\n",
    "ufe_raw = veri_cek_evds(\"TP.TUFE1YI.T1\")\n",
    "if ufe_raw:\n",
    "    vals = [float(x[\"TP_TUFE1YI_T1\"]) for x in ufe_raw if x.get(\"TP_TUFE1YI_T1\")]\n",
    "    dates = [x[\"Tarih\"] for x in ufe_raw if x.get(\"TP_TUFE1YI_T1\")]\n",
    "    for i in range(len(vals)):\n",
    "        if \"2023\" in dates[i] or \"2024\" in dates[i] or \"2025\" in dates[i]:\n",
    "            aylik = ((vals[i] - vals[i-1])/vals[i-1])*100 if i>0 else 0\n",
    "            yillik = ((vals[i] - vals[i-12])/vals[i-12])*100 if i>=12 else 0\n",
    "            ufe_list.append({\"tarih\": dates[i], \"aylik\": round(aylik, 2), \"yillik\": round(yillik, 2)})\n",
    "\n",
    "# --- D) CARİ DENGE ---\n",
    "cari_list = []\n",
    "cari_raw = veri_cek_evds(\"TP.HARICCARIACIK.K1-TP.HARICCARIACIK.K10\")\n",
    "if cari_raw:\n",
    "    df_cari = pd.DataFrame(cari_raw)\n",
    "    df_cari['TP_HARICCARIACIK_K1'] = pd.to_numeric(df_cari['TP_HARICCARIACIK_K1'])\n",
    "    df_cari['TP_HARICCARIACIK_K10'] = pd.to_numeric(df_cari['TP_HARICCARIACIK_K10'])\n",
    "    df_cari['Cari_Yillik'] = df_cari['TP_HARICCARIACIK_K1'].rolling(window=12).sum()\n",
    "    df_cari['Cekirdek_Yillik'] = df_cari['TP_HARICCARIACIK_K10'].rolling(window=12).sum()\n",
    "    for _, row in df_cari.iterrows():\n",
    "        yil = row[\"Tarih\"].split(\"-\")[0]\n",
    "        if int(yil) >= 2023 and pd.notnull(row['Cari_Yillik']):\n",
    "            cari_list.append({\n",
    "                \"tarih\": row[\"Tarih\"],\n",
    "                \"cari_aylik\": int(row[\"TP_HARICCARIACIK_K1\"]),\n",
    "                \"cari_yillik\": int(row[\"Cari_Yillik\"]),\n",
    "                \"cekirdek_aylik\": int(row[\"TP_HARICCARIACIK_K10\"]),\n",
    "                \"cekirdek_yillik\": int(row[\"Cekirdek_Yillik\"])\n",
    "            })\n",
    "\n",
    "# --- E) BÜTÇE DENGESİ ---\n",
    "butce_list = []\n",
    "if os.path.exists(PATH_BUTCE):\n",
    "    try:\n",
    "        df = pd.read_excel(PATH_BUTCE)\n",
    "        df = df.dropna(subset=[\"Tarih\"])\n",
    "        for _, row in df.iterrows():\n",
    "            tarih = str(row[\"Tarih\"])\n",
    "            if isinstance(row[\"Tarih\"], pd.Timestamp): tarih = row[\"Tarih\"].strftime('%d-%m-%Y')\n",
    "            if \"2023\" in tarih or \"2024\" in tarih or \"2025\" in tarih:\n",
    "                butce_list.append({\n",
    "                    \"tarih\": tarih,\n",
    "                    \"butce_aylik\": clean_nan(float(row[\"Bütçe Dengesi Aylık\"])),\n",
    "                    \"butce_yillik\": clean_nan(float(row[\"Bütçe Dengesi Yıllık\"])),\n",
    "                    \"faizdisi_aylik\": clean_nan(float(row[\"Faiz Dışı Denge Aylık\"])),\n",
    "                    \"faizdisi_yillik\": clean_nan(float(row[\"Faiz Dışı Denge Yıllık\"]))\n",
    "                })\n",
    "    except: pass\n",
    "\n",
    "# --- F) HAZİNE NAKİT ---\n",
    "nakit_list = []\n",
    "if os.path.exists(PATH_NAKIT):\n",
    "    try:\n",
    "        df = pd.read_excel(PATH_NAKIT)\n",
    "        df = df.dropna(subset=[\"Tarih\"])\n",
    "        for _, row in df.iterrows():\n",
    "            tarih = str(row[\"Tarih\"])\n",
    "            if isinstance(row[\"Tarih\"], pd.Timestamp): tarih = row[\"Tarih\"].strftime('%d-%m-%Y')\n",
    "            if \"2023\" in tarih or \"2024\" in tarih or \"2025\" in tarih:\n",
    "                nakit_list.append({\n",
    "                    \"tarih\": tarih,\n",
    "                    \"nakit_aylik\": clean_nan(float(row[\"Nakit Dengesi Aylık\"])),\n",
    "                    \"nakit_yillik\": clean_nan(float(row[\"Nakit Dengesi Yıllık\"])),\n",
    "                    \"faizdisi_aylik\": clean_nan(float(row[\"Faiz Dışı Nakit Denge Aylık\"])),\n",
    "                    \"faizdisi_yillik\": clean_nan(float(row[\"Faiz Dışı Nakit Denge Yıllık\"]))\n",
    "                })\n",
    "    except: pass\n",
    "\n",
    "# --- G) İŞGÜCÜ ---\n",
    "atıl_dict = {}\n",
    "if os.path.exists(PATH_ATIL):\n",
    "    try:\n",
    "        df = pd.read_excel(PATH_ATIL)\n",
    "        df.columns = [c.strip() for c in df.columns] # Column isimlerini temizle\n",
    "        if \"Tarih\" in df.columns and \"Atıl İşgücü\" in df.columns:\n",
    "            df = df.dropna(subset=[\"Tarih\", \"Atıl İşgücü\"])\n",
    "            for _, row in df.iterrows():\n",
    "                # Tarih formatlama (YYYY-MM-DD olarak standardize ediyoruz)\n",
    "                try:\n",
    "                    ts = pd.to_datetime(row[\"Tarih\"], dayfirst=True)\n",
    "                    t_str = ts.strftime('%Y-%m-%d')\n",
    "                    \n",
    "                    val = float(row[\"Atıl İşgücü\"])\n",
    "                    # Eğer oran olarak girildiyse (örn: 0.23 -> %23), 100 ile çarpıp yüzdelik yapıyoruz\n",
    "                    if val < 1.0 and val > 0:\n",
    "                        val = val * 100\n",
    "                        \n",
    "                    atıl_dict[t_str] = val\n",
    "                except: pass\n",
    "    except Exception as e:\n",
    "        print(f\"Excel hatası (Atıl İşgücü): {e}\")\n",
    "\n",
    "isgucu_list = []\n",
    "isgucu_raw = veri_cek_evds(\"TP.TIG08-TP.TIG06\")\n",
    "\n",
    "if isgucu_raw:\n",
    "    for item in isgucu_raw:\n",
    "        raw_tarih = item[\"Tarih\"]\n",
    "        \n",
    "        # EVDS tarihini parse edip formatlayalım\n",
    "        try:\n",
    "            dt = pd.to_datetime(raw_tarih, dayfirst=True)\n",
    "            lookup_date = dt.strftime('%Y-%m-%d')\n",
    "            year = dt.year\n",
    "            \n",
    "            if year >= 2023:\n",
    "                # Sözlükten veriyi çek (Yoksa None döner)\n",
    "                atil_val = atıl_dict.get(lookup_date)\n",
    "                \n",
    "                # Sadece veri varsa ekle (İsteğe bağlı, EVDS verisi varsa ekleyelim, atıl boş gelebilir)\n",
    "                if item.get(\"TP_TIG08\"):\n",
    "                    isgucu_list.append({\n",
    "                        \"tarih\": raw_tarih, \n",
    "                        \"issizlik\": float(item[\"TP_TIG08\"]),\n",
    "                        \"katilim\": float(item[\"TP_TIG06\"]),\n",
    "                        \"atil\": atil_val\n",
    "                    })\n",
    "        except: pass\n",
    "\n",
    "# --- H) TCMB FONLAMA ---\n",
    "fon_list = []\n",
    "# Serileri parametre olarak tanımlayalım\n",
    "series = \"TP.APIFON4-TP.BISTTLREF.ORAN-TP.APIFON3\"\n",
    "fon_raw = veri_cek_evds(series)\n",
    "\n",
    "# Hata ayıklama için ilk veriyi kontrol etmekte fayda var (print ile)\n",
    "# print(fon_raw[0]) \n",
    "\n",
    "for item in fon_raw:\n",
    "    tarih = item[\"Tarih\"]\n",
    "    \n",
    "    # DÜZELTME 1: Yılı almak için son parçayı alıyoruz (GG-AA-YYYY varsayımıyla)\n",
    "    # Eğer veri YYYY-MM-DD geliyorsa senin kodun doğruydu, \n",
    "    # ama boş dönüyorsa %99 ihtimalle format GG-AA-YYYY'dir.\n",
    "    yil_str = tarih.split(\"-\")[-1] \n",
    "    \n",
    "    # Güvenlik önlemi: Yıl verisi bazen boş gelebilir, kontrol edelim\n",
    "    if not yil_str.isdigit():\n",
    "        continue\n",
    "        \n",
    "    yil = int(yil_str)\n",
    "    \n",
    "    # TP_APIFON4 verisinin None olmadığından emin olalım\n",
    "    if yil >= 2023 and item.get(\"TP_APIFON4\") is not None:\n",
    "        try:\n",
    "            fon_list.append({\n",
    "                \"tarih\": tarih,\n",
    "                \"aofm\": float(item[\"TP_APIFON4\"]),\n",
    "                # get kullanırken default değer atamak iyidir\n",
    "                \"tlref\": float(item.get(\"TP_BISTTLREF_ORAN\") or 0), \n",
    "                \"net_fonlama\": int(float(item.get(\"TP_APIFON3\") or 0))\n",
    "            })\n",
    "        except ValueError:\n",
    "            # Veri bazen boş string \"\" gelebilir, float'a çevrilemez\n",
    "            continue\n",
    "            \n",
    "# ==========================================\n",
    "# I. GSYH ÖNCÜ GÖSTERGELERİ\n",
    "# ==========================================\n",
    "oncu_gostergeler_list = []\n",
    "\n",
    "# --- 1. SANAYİ (EVDS'den çekilmeye devam edecek) ---\n",
    "\n",
    "# --- 2. DİĞERLERİ (Excel'den çekilecek) ---\n",
    "# Hizmet, Ticaret, Perakende, İnşaat, Sanayi\n",
    "\n",
    "excel_mapping = {\n",
    "    \"Hizmet\": \"hizmet\",\n",
    "    \"Ticaret\": \"ticaret\",\n",
    "    \"Perakende\": \"perakende\",\n",
    "    \"İnşaat\": \"insaat\",\n",
    "    \"Sanayi\": \"sanayi\"\n",
    "}\n",
    "\n",
    "if os.path.exists(PATH_GSYH_ONCU):\n",
    "    try:\n",
    "        df_oncu = pd.read_excel(PATH_GSYH_ONCU)\n",
    "        \n",
    "        # Tarih formatını garantiye al\n",
    "        df_oncu[\"Tarih\"] = pd.to_datetime(df_oncu[\"Tarih\"])\n",
    "        df_oncu = df_oncu.sort_values(\"Tarih\").reset_index(drop=True)\n",
    "        \n",
    "        # Her bir tür için işlem yap\n",
    "        for col_name, json_key in excel_mapping.items():\n",
    "            if col_name in df_oncu.columns:\n",
    "                temp_series = []\n",
    "                vals = df_oncu[col_name].values\n",
    "                dates = df_oncu[\"Tarih\"].values\n",
    "                \n",
    "                for i in range(len(vals)):\n",
    "                    current_date = pd.to_datetime(dates[i])\n",
    "                    \n",
    "                    if current_date.year >= 2023:\n",
    "                        # Yıllık değişim hesabı (12 ay öncesine göre)\n",
    "                        if i >= 12:\n",
    "                            val_now = vals[i]\n",
    "                            val_prev = vals[i-12]\n",
    "                            if val_prev != 0:\n",
    "                                yillik_degisim = ((val_now - val_prev) / val_prev) * 100\n",
    "                            else:\n",
    "                                yillik_degisim = 0\n",
    "                        else:\n",
    "                            yillik_degisim = 0\n",
    "                        \n",
    "                        # Tarih formatını EVDS gibi yapalım (İsteğe bağlı, burada dd-mm-yyyy kullanıyorum)\n",
    "                        tarih_str = current_date.strftime('%d-%m-%Y')\n",
    "                        \n",
    "                        temp_series.append({\n",
    "                            \"tarih\": tarih_str,\n",
    "                            \"deger\": float(vals[i]),\n",
    "                            \"yillik\": round(yillik_degisim, 1)\n",
    "                        })\n",
    "                \n",
    "                oncu_gostergeler_list.append({\n",
    "                    \"tur\": json_key,\n",
    "                    \"data\": temp_series\n",
    "                })\n",
    "            else:\n",
    "                print(f\"Uyarı: Excel dosyasında '{col_name}' sütunu bulunamadı.\")\n",
    "                \n",
    "    except Exception as e:\n",
    "        print(f\"GSYH Öncü Excel okuma hatası: {e}\")\n",
    "else:\n",
    "    print(f\"Hata: GSYH Öncü Excel dosyası bulunamadı: {PATH_GSYH_ONCU}\")\n",
    "# ==========================================\n",
    "# 2. İKİNCİL GÖSTERGELER\n",
    "# ==========================================\n",
    "\n",
    "# --- A) İMALAT SANAYİ PMI VERİSİNİ HAZIRLAMA ---\n",
    "pmi_dict = {}\n",
    "\n",
    "if os.path.exists(PATH_PMI):\n",
    "    try:\n",
    "        df = pd.read_excel(PATH_PMI)\n",
    "        df = df.dropna(subset=[\"Tarih\", \"İmalat Sanayi PMI\"])\n",
    "        \n",
    "        # Excel'deki tarihi datetime objesine çevir\n",
    "        df[\"Tarih\"] = pd.to_datetime(df[\"Tarih\"])\n",
    "        \n",
    "        for _, row in df.iterrows():\n",
    "            # Standardize et: YYYY-MM-DD (Örn: 2023-01-01)\n",
    "            t_str = row[\"Tarih\"].strftime('%Y-%m-%d')\n",
    "            pmi_dict[t_str] = float(row[\"İmalat Sanayi PMI\"])\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"Excel okuma hatası: {e}\")\n",
    "else:\n",
    "    print(\"Excel dosyası bulunamadı.\")\n",
    "\n",
    "# --- B) EVDS VERİSİ İLE BİRLEŞTİRME (DÜZELTİLMİŞ) ---\n",
    "imalat_list = []\n",
    "\n",
    "# EVDS'den KKO verisini çekiyoruz\n",
    "kko_raw = veri_cek_evds(\"TP.KKO2.IS.TOP\") \n",
    "\n",
    "if 'kko_raw' in locals() and kko_raw:\n",
    "    for item in kko_raw:\n",
    "        raw_tarih = item[\"Tarih\"] \n",
    "        \n",
    "        try:\n",
    "            dt_object = pd.to_datetime(raw_tarih)\n",
    "            lookup_key = dt_object.strftime('%Y-%m-%d')\n",
    "            \n",
    "            if dt_object.year >= 2023:\n",
    "                # 1. PMI Verisini Sözlükten Çek (Yoksa None gelir)\n",
    "                pmi_degeri = pmi_dict.get(lookup_key)\n",
    "                \n",
    "                # 2. KKO Verisini Al\n",
    "                val_kko_raw = item.get(\"TP_KKO2_IS_TOP\")\n",
    "                \n",
    "                # 3. KONTROL: Her iki veri de MEVCUTSA ve 0'dan BÜYÜKSE listeye ekle.\n",
    "                # Böylece PMI henüz açıklanmadıysa o ayı listeye hiç almayız,\n",
    "                # grafik ve panel bir önceki (tam olan) ayda durur.\n",
    "                if pmi_degeri is not None and val_kko_raw is not None:\n",
    "                    val_kko = float(val_kko_raw)\n",
    "                    \n",
    "                    if pmi_degeri > 0 and val_kko > 0:\n",
    "                        imalat_list.append({\n",
    "                            \"tarih\": lookup_key,\n",
    "                            \"kko\": val_kko,\n",
    "                            \"pmi\": pmi_degeri\n",
    "                        })\n",
    "                        \n",
    "        except Exception as err:\n",
    "            print(f\"Hata ({raw_tarih}): {err}\")\n",
    "else:\n",
    "    print(\"kko_raw verisi yok.\")\n",
    "\n",
    "# --- B) GÜVEN ENDEKSLERİ ---\n",
    "guven_list = []\n",
    "# İki seriyi tek istekte çekiyoruz: Tüketici Güven ve Reel Kesim Güven\n",
    "guven_raw = veri_cek_evds(\"TP.TG2.Y01-TP.GY1.N2.MA\")\n",
    "\n",
    "for item in guven_raw:\n",
    "    tarih = item[\"Tarih\"]\n",
    "    yil = tarih.split(\"-\")[0]\n",
    "    \n",
    "    if int(yil) >= 2023:\n",
    "        # EVDS, JSON anahtarlarında noktaları alt çizgiye çevirir.\n",
    "        # Bu yüzden \"TP.GY1.N2.MA\" yerine \"TP_GY1_N2_MA\" kullanmalıyız.\n",
    "        \n",
    "        # Veri bazen boş string \"\" veya None gelebilir, güvenli dönüşüm yapalım:\n",
    "        val_tuketici = item.get(\"TP_TG2_Y01\")\n",
    "        val_reel = item.get(\"TP_GY1_N2_MA\") # <--- Düzeltilen kısım (Nokta yerine Alt Çizgi)\n",
    "\n",
    "        guven_list.append({\n",
    "            \"tarih\": tarih,\n",
    "            # Değer varsa float'a çevir, yoksa 0 ata\n",
    "            \"tuketici\": int(float(val_tuketici)) if val_tuketici else 0,\n",
    "            \"reel\": float(val_reel) if val_reel else 0\n",
    "        })\n",
    "\n",
    "# ==========================================\n",
    "# 3. ABD & EURO (FRED)\n",
    "# ==========================================\n",
    "\n",
    "# --- FED FAİZ ---\n",
    "fed_list = []\n",
    "df_fed = veri_cek_fred(\"DFEDTARU\") \n",
    "df_effr = veri_cek_fred(\"EFFR\")     \n",
    "df_lower = veri_cek_fred(\"DFEDTARL\")\n",
    "\n",
    "if not df_fed.empty and not df_effr.empty and 'DATE' in df_fed.columns and 'DATE' in df_effr.columns:\n",
    "    m = pd.merge(df_fed, df_effr, on=\"DATE\", how=\"inner\", suffixes=('_U', '_E'))\n",
    "    if not df_lower.empty and 'DATE' in df_lower.columns:\n",
    "        m = pd.merge(m, df_lower, on=\"DATE\", how=\"inner\")\n",
    "    \n",
    "    m = m[m['DATE'].dt.year >= 2023]\n",
    "    for _, r in m.iterrows():\n",
    "        if len(r) >= 4:\n",
    "            fed_list.append({\n",
    "                \"tarih\": r[\"DATE\"].strftime('%d-%m-%Y'),\n",
    "                \"ust\": clean_nan(float(r.iloc[1])), \n",
    "                \"efektif\": clean_nan(float(r.iloc[2])), \n",
    "                \"alt\": clean_nan(float(r.iloc[3]))\n",
    "            })\n",
    "\n",
    "# --- ABD TÜFE ---\n",
    "uscpi_list = []\n",
    "df_uscpi = veri_cek_fred(\"CPIAUCSL\")\n",
    "if not df_uscpi.empty and 'DATE' in df_uscpi.columns:\n",
    "    col_name = df_uscpi.columns[1]\n",
    "    df_uscpi['MoM'] = df_uscpi[col_name].pct_change(1)*100\n",
    "    df_uscpi['YoY'] = df_uscpi[col_name].pct_change(12)*100\n",
    "    df_uscpi = df_uscpi[df_uscpi['DATE'].dt.year >= 2023]\n",
    "    for _, r in df_uscpi.iterrows():\n",
    "        if pd.notnull(r['MoM']):\n",
    "            uscpi_list.append({\n",
    "                \"tarih\": r[\"DATE\"].strftime('%d-%m-%Y'), \n",
    "                \"aylik\": round(r[\"MoM\"],1), \n",
    "                \"yillik\": round(r[\"YoY\"],1)\n",
    "            })\n",
    "\n",
    "# --- ECB FAİZ ---\n",
    "ecb_list = []\n",
    "df1 = veri_cek_fred(\"ECBDFR\")\n",
    "df2 = veri_cek_fred(\"ECBMRRFR\")\n",
    "df3 = veri_cek_fred(\"ECBMLFR\")\n",
    "if not df1.empty and not df2.empty and not df3.empty:\n",
    "    m = pd.merge(df1, df2, on=\"DATE\", how=\"outer\")\n",
    "    m = pd.merge(m, df3, on=\"DATE\", how=\"outer\")\n",
    "    m.fillna(method='ffill', inplace=True)\n",
    "    m = m[m['DATE'].dt.year >= 2023]\n",
    "    for _, r in m.iterrows():\n",
    "        if len(r) >= 4:\n",
    "            ecb_list.append({\n",
    "                \"tarih\": r[\"DATE\"].strftime('%d-%m-%Y'),\n",
    "                \"mevduat\": clean_nan(float(r.iloc[1])),\n",
    "                \"refinans\": clean_nan(float(r.iloc[2])),\n",
    "                \"marjinal\": clean_nan(float(r.iloc[3]))\n",
    "            })\n",
    "\n",
    "# --- EURO TÜFE ---\n",
    "eurocpi_list = []\n",
    "df_eu = veri_cek_fred(\"CP0000EZ19M086NEST\")\n",
    "if not df_eu.empty and 'DATE' in df_eu.columns:\n",
    "    col_name = df_eu.columns[1]\n",
    "    df_eu['MoM'] = df_eu[col_name].pct_change(1)*100\n",
    "    df_eu['YoY'] = df_eu[col_name].pct_change(12)*100\n",
    "    df_eu = df_eu[df_eu['DATE'].dt.year >= 2023]\n",
    "    for _, r in df_eu.iterrows():\n",
    "        if pd.notnull(r['MoM']):\n",
    "            eurocpi_list.append({\n",
    "                \"tarih\": r[\"DATE\"].strftime('%d-%m-%Y'), \n",
    "                \"aylik\": round(r[\"MoM\"],1), \n",
    "                \"yillik\": round(r[\"YoY\"],1)\n",
    "            })\n",
    "\n",
    "# ==========================================\n",
    "# KAYDET VE TEMİZLE\n",
    "# ==========================================\n",
    "\n",
    "final_data = {\n",
    "    \"gsyh\": gsyh_list, \n",
    "    \"tufe\": tufe_list, \n",
    "    \"ufe\": ufe_list, \n",
    "    \"cari\": cari_list,\n",
    "    \"butce\": butce_list, \n",
    "    \"nakit\": nakit_list, \n",
    "    \"isgucu\": isgucu_list, \n",
    "    \"fonlama\": fon_list,\n",
    "    \"imalat\": imalat_list, \n",
    "    \"guven\": guven_list, \n",
    "    \"fed\": fed_list, \n",
    "    \"uscpi\": uscpi_list,\n",
    "    \"ecb\": ecb_list, \n",
    "    \"eurocpi\": eurocpi_list,\n",
    "    \"gsyh_oncu\": oncu_gostergeler_list  # <--- BURAYI EKLE\n",
    "}\n",
    "\n",
    "# Recursively clean NaNs in the final structure\n",
    "def sanitize_json(obj):\n",
    "    if isinstance(obj, dict):\n",
    "        return {k: sanitize_json(v) for k, v in obj.items()}\n",
    "    elif isinstance(obj, list):\n",
    "        return [sanitize_json(i) for i in obj]\n",
    "    elif isinstance(obj, float):\n",
    "        if math.isnan(obj) or math.isinf(obj):\n",
    "            return None\n",
    "    return obj\n",
    "\n",
    "final_clean = sanitize_json(final_data)\n",
    "\n",
    "with open('veri.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(final_clean, f, ensure_ascii=False, indent=4)\n",
    "\n",
    "print(\"✅ GÜNCELLENDİ!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
